services:
  mariadb:
    # image: mariadb
    build: ./requirements/mariadb/
    volumes:
      - db_vol:/var/lib/mysql
    networks:
      - inception_net
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      # MARIADB_ROOT_PASSWORD: geheim
      MARIADB_PASSWORD_FILE: /run/secrets/db_password
      # MARIADB_PASSWORD: geheim
      MARIADB_USER: blog
      MARIADB_DATABASE: wordpress
    secrets:
      - db_root_password
      - db_password

  # wordpress:
  #   image: wordpress
  #   networks:
  #     - inception_net
  #   ports:
  #     # - 4443:443
  #     - 8080:80
  #   environment:
  #     WORDPRESS_DB_HOST: mariadb
  #     WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
  #     # WORDPRESS_DB_PASSWORD: geheim
  #     WORDPRESS_DB_USER: blog
  #     WORDPRESS_DB_NAME: wordpress
  #   secrets:
  #     - db_password
    
  #  nginx:
  #  build: ./requirements/nginx
  #  networks:
  #    - inception_net
  #  ports:
  #    - 8080:80
  #    - 443:80

networks:
  inception_net:
    driver: bridge

volumes:
  db_vol:
    name: inception_database
    # driver: local
    # driver_opts:
    #   type: none
    #   device: ${VOLUME_PATH}/database
    #   o: bind 

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
